
[project]

name = "envsync"
version = "0.1.0"
description = "Sync your env to any machine"
requires-python = ">=3.8"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]